-- Approved, non-sensitive configuration only. Conflict-safe inserts do not
-- overwrite later admin edits. No transactional or fabricated records.

insert into public.package_catalog
  (offer_key, name, build_route, supported_platforms, base_price_usd, level, active, display_order, description, included_capability_keys, limits, support_days, revision_rounds)
values
  ('platform_launch','Launch System','platform',array['systeme_io','gohighlevel'],1500,1,true,10,'Best for one offer, one audience, and one primary conversion action.',array['responsive_build','lead_form','confirmation_page','basic_booking_or_checkout','basic_email_follow_up','basic_analytics'],
   jsonb_build_object('included_features',jsonb_build_array('Strategy and conversion-path planning for one offer','One landing page or compact conversion website of up to five core sections','Responsive desktop, tablet, and mobile setup','One lead form, application form, or inquiry form','One thank-you or confirmation page','One basic booking or checkout connection','One confirmation email and one basic follow-up sequence of up to three emails','Basic tags, contact fields, and simple segmentation','Basic analytics and conversion-event setup','Domain connection guidance','Launch testing and handover')),0,1),
  ('platform_growth','Growth System','platform',array['systeme_io','gohighlevel'],2500,2,true,20,'Best for a connected lead-to-booking, enrollment, or order journey.',array['multi_step_funnel','lead_qualification','booking_or_checkout','crm_pipeline','email_follow_up','basic_onboarding','two_standard_integrations'],
   jsonb_build_object('included_features',jsonb_build_array('Everything in Launch System where applicable','Multi-step funnel or conversion website of up to five primary pages or steps','Lead qualification or application flow','Booking, checkout, enrollment, or deposit connection','CRM pipeline with core stages','Automated confirmation, reminders, and follow-up sequence of up to seven emails or messages','Basic onboarding workflow','Audience or offer segmentation','Up to two standard third-party integrations','Funnel and pipeline testing','Recorded handover or training session')),0,2),
  ('platform_scale','Scale System','platform',array['systeme_io','gohighlevel'],4000,3,true,30,'Best for multiple offers, connected pipelines, and advanced platform-native automation.',array['multiple_offers','advanced_pipeline','conditional_workflows','extended_nurture','platform_onboarding_area','four_standard_integrations','basic_reporting'],
   jsonb_build_object('included_features',jsonb_build_array('Everything in Growth System where applicable','Up to two offers, funnels, or audience paths','Advanced pipeline stages and opportunity automation','Conditional workflows using the selected platform native capabilities','Extended email or SMS nurture of up to twelve messages','Client or student onboarding area using platform-native features where available','Up to four standard integrations','Basic reporting dashboard using available platform data','Team access and permissions supported by the client subscription','End-to-end quality assurance','Training and 30-day post-launch technical support')),30,2),
  ('custom_starter','Custom Starter','custom',array['custom_app'],3000,1,true,40,'Best for a focused minimum viable product with one clear internal or customer-facing workflow.',array['focused_module','single_user_type_auth','core_crud_status_workflow','simple_admin_view','basic_notification'],
   jsonb_build_object('included_features',jsonb_build_array('Discovery session and simplified workflow map','Custom responsive interface for one focused module','Supabase project, database, and basic security setup','Authentication for one primary user type','One core create, view, edit, and status workflow','Simple admin management view','Basic form validation and record search or filtering','One basic notification or confirmation workflow','Deployment and environment configuration','Testing, handover, and 30-day technical support')),30,1),
  ('custom_foundation','Custom Foundation','custom',array['custom_app'],5000,2,true,50,'Best for a production-ready custom app with a connected admin and user experience.',array['admin_and_user_auth','two_core_workflows','admin_dashboard','file_upload','two_standard_integrations','basic_activity_history'],
   jsonb_build_object('included_features',jsonb_build_array('Everything in Custom Starter where applicable','Detailed workflow and data-model planning','Supabase database, authentication, storage, and access policies','Secure authentication for one primary user type plus admin','Up to two connected core workflows','Custom admin dashboard with operational status tracking','File or image upload capability','Expanded search, filtering, and record-management functions','Up to two standard third-party integrations','Basic analytics and activity history','Email notifications or workflow confirmations','Testing, handover, and 30-day technical support')),30,2),
  ('custom_growth','Custom Growth','custom',array['custom_app'],7500,3,true,60,'Best for several connected workflows, portals, roles, and dashboards.',array['three_user_roles','basic_custom_portal_module','custom_dashboard_reporting_module','multiple_workflows','three_standard_integrations','operational_reporting'],
   jsonb_build_object('included_features',jsonb_build_array('Everything in Custom Foundation where applicable','Up to three user roles with permission-based views','Client, student, customer, employee, or partner portal','Multiple connected business workflows','Advanced admin dashboard and status tracking','File upload or document-management capability','Search, filtering, and operational reporting','Up to three standard third-party integrations','Automated notifications and workflow triggers','Audit-friendly activity history for important actions','Supabase row-level security policies for each supported role','Training and 60-day technical support')),60,2),
  ('custom_complete','Complete Custom System','custom',array['custom_app'],10000,4,true,70,'Best for complex operations, multiple departments, inventory, delivery, or specialized business rules.',array['advanced_roles','multiple_portals','custom_approvals','advanced_reporting','complex_business_rules','expanded_integrations'],
   jsonb_build_object('starting_price',true,'requires_scope_review',true,'included_features',jsonb_build_array('Everything in Custom Growth where applicable','Advanced roles and permission structure','Multiple portals or department-specific workspaces','Inventory, production, order, delivery, or resource-management modules as scoped','Custom approvals and multi-stage workflows','Advanced reporting and management dashboards','Complex calculations or business rules','Expanded integration requirements','Data migration plan where required','Advanced Supabase data relationships, storage policies, and server-side functions as required','Security review and extended quality assurance','Phased rollout plan','Training and 90-day technical support')),90,3)
on conflict (offer_key) do nothing;

insert into public.addon_catalog
  (addon_key,name,description,starting_price_usd,pricing_unit,allowed_build_routes,included_in_offer_keys,requires_scope_review,active,display_order)
values
  ('conversion_copywriting','Conversion copywriting','Conversion copywriting for core pages or steps.',500,'Up to five core pages/steps',array['platform','custom'],'{}',false,true,10),
  ('additional_copywriting','Additional copywriting','Copywriting beyond the core included scope.',150,'Per additional page/step',array['platform','custom'],'{}',false,true,20),
  ('image_sourcing_selection','Image sourcing and selection','Image sourcing and selection for the project.',200,'Per project set',array['platform','custom'],'{}',false,true,30),
  ('image_editing_optimization','Image editing and optimization','Editing and web optimization for supplied or sourced images.',300,'Up to 20 images',array['platform','custom'],'{}',false,true,40),
  ('mini_brand_direction','Mini brand direction','Colors, typography, and a basic visual guide.',400,'Colors, type, and basic visual guide',array['platform','custom'],'{}',false,true,50),
  ('additional_page_step','Additional landing/page step','An additional standard landing page or funnel step.',250,'Per standard page/step',array['platform','custom'],'{}',false,true,60),
  ('advanced_booking_setup','Advanced booking setup','An advanced booking workflow.',350,'Per booking workflow',array['platform','custom'],'{}',false,true,70),
  ('checkout_payment_integration','Checkout/payment integration','A standard checkout or payment gateway flow.',400,'Per standard gateway/flow',array['platform','custom'],array['platform_launch','platform_growth','platform_scale'],false,true,80),
  ('additional_email_automation','Additional email automation','An additional email sequence.',300,'Per sequence of up to five emails',array['platform','custom'],'{}',false,true,90),
  ('sms_automation_setup','SMS automation setup','An SMS workflow; usage is billed separately.',350,'Per workflow; usage billed separately',array['platform','custom'],'{}',false,true,100),
  ('additional_crm_pipeline','Additional CRM pipeline','An additional CRM pipeline.',500,'Per pipeline',array['platform','custom'],'{}',false,true,110),
  ('advanced_onboarding_workflow','Advanced onboarding workflow','An advanced onboarding workflow.',500,'Per workflow',array['platform','custom'],array['platform_scale'],false,true,120),
  ('platform_membership_course_area','Platform-native membership/course area','A membership or course area using supported platform-native features.',750,'Per area/program',array['platform'],'{}',false,true,130),
  ('basic_custom_portal_module','Basic custom portal module','A basic portal module for the Custom App route.',1500,'Per module; Custom App route',array['custom'],array['custom_growth','custom_complete'],false,true,140),
  ('custom_dashboard_reporting_module','Custom dashboard/reporting module','A custom dashboard or reporting module.',1500,'Per module; Custom App route',array['custom'],array['custom_foundation','custom_growth','custom_complete'],false,true,150),
  ('custom_order_management_module','Custom order-management module','A custom order-management module.',2000,'Per module; Custom App route',array['custom'],'{}',false,true,160),
  ('inventory_production_module','Inventory/production module','A custom inventory or production module.',2500,'Starting price; Custom App route',array['custom'],'{}',true,true,170),
  ('standard_third_party_integration','Standard third-party integration','A standard supported third-party integration.',350,'Per integration',array['platform','custom'],array['platform_growth','platform_scale','custom_foundation','custom_growth','custom_complete'],false,true,180),
  ('complex_custom_api_integration','Complex/custom API integration','A complex or custom API integration requiring review.',750,'Per integration after review',array['platform','custom'],'{}',true,true,190),
  ('content_data_migration','Content or data migration','Content or data migration based on volume and cleanup needs.',500,'Based on volume and cleanup',array['platform','custom'],'{}',true,true,200),
  ('additional_revision_round','Additional revision round','One additional revision round.',300,'Per round',array['platform','custom'],'{}',false,true,210)
on conflict (addon_key) do nothing;

-- Not seeded because the blueprint does not yet provide complete approved data:
-- quiz_definitions: questions exist, but complete scoring_rules/version approval does not.
-- projects: no complete real project rows are present in the blueprint/repository.
-- site_content: no complete approved document payloads are present in the blueprint.
