import {
  CORTEX_VERSION,
  QUESTION_SET_VERSION,
  type AudienceKey,
  type QuestionDefinition,
  type QuizDefinition,
  type QuizOption,
  type SignalTag,
} from "./types.ts";

export const APPROVED_SIGNAL_TAGS = [
  "credibility", "lead_generation", "booking", "enrollment", "checkout",
  "follow_up", "pipeline", "onboarding", "course_delivery", "disconnected_tools",
  "multiple_offers", "portal", "dashboard", "custom_orders", "approvals",
  "inventory", "multiple_roles", "integration", "order_tracking", "migration",
  "simple_scope", "no_system_effect",
] as const satisfies readonly SignalTag[];

const option = (
  key: string,
  label: string,
  signals: readonly SignalTag[],
  extra: Omit<QuizOption, "key" | "label" | "signals"> = {},
): QuizOption => ({ key, label, signals, ...extra });

const question = (
  key: string,
  prompt: string,
  options: readonly QuizOption[],
  selection: "single" | "multiple" = "single",
  scope: "audience" | "universal" = "audience",
  helpText?: string,
  maxSelections?: number,
): QuestionDefinition => ({ key, prompt, options, selection, scope, helpText, maxSelections, required: true });

const demandQuestion = question("q5_demand_health", "How consistently are people already showing interest in your business?", [
  option("demand_steady_some_dropoff", "We receive steady inquiries or leads but lose some before conversion.", ["no_system_effect"]),
  option("demand_inconsistent", "We receive inquiries, but they are inconsistent.", ["no_system_effect"]),
  option("demand_referrals_social", "Most business comes from referrals or social media messages.", ["no_system_effect"]),
  option("demand_traffic_low_action", "We have an audience or website traffic but few people take the next step.", ["no_system_effect"]),
  option("demand_early_awareness", "We are still building awareness and receive very little traffic.", ["no_system_effect"]),
], "single", "universal");

const timelineQuestion = question("q9_timeline", "When would you like to begin?", [
  option("timeline_ready_now", "Ready now.", [], { readiness: "ready_now" }),
  option("timeline_within_30_days", "Within 30 days.", [], { readiness: "within_30_days" }),
  option("timeline_within_1_2_months", "Within one to two months.", [], { readiness: "planning_1_2_months" }),
  option("timeline_researching", "Researching for later.", [], { readiness: "researching" }),
], "single", "universal");

const platformQuestion = question("q10_platform", "Do you already have a platform you would prefer us to work with?", [
  option("platform_recommend", "Recommend the best option for me.", []),
  option("platform_systeme", "Systeme.io.", [], { platformPreference: "systeme_io" }),
  option("platform_highlevel", "HighLevel.", [], { platformPreference: "gohighlevel" }),
  option("platform_custom_app", "I think I need a custom-built system.", [], { platformPreference: "custom_app" }),
  option("platform_other", "I already use another platform.", ["integration"]),
  option("platform_unsure", "I am not sure.", []),
], "single", "universal");

const coachesQuestions = [
  question("q1_business_model", "How do you currently deliver your expertise?", [
    option("coach_model_one_to_one", "One-to-one coaching or consulting.", ["booking", "pipeline"]),
    option("coach_model_group", "Group coaching or cohort program.", ["enrollment", "onboarding"]),
    option("coach_model_course", "Online course.", ["enrollment", "checkout", "course_delivery"]),
    option("coach_model_membership", "Membership or community.", ["enrollment", "course_delivery", "portal"]),
    option("coach_model_workshops", "Workshops or live training.", ["enrollment", "checkout"]),
    option("coach_model_combination", "A combination of several offers.", ["multiple_offers"]),
  ]),
  question("q2_goal", "What would you most like your business to achieve?", [
    option("coach_goal_book_calls", "Book more qualified coaching or discovery calls.", ["booking", "lead_generation"]),
    option("coach_goal_enroll_students", "Enroll more students.", ["enrollment", "lead_generation"]),
    option("coach_goal_sell_offers", "Sell more courses, workshops, or memberships.", ["enrollment", "checkout"]),
    option("coach_goal_improve_delivery", "Improve student onboarding and learning delivery.", ["onboarding", "course_delivery"]),
    option("coach_goal_retention", "Increase student engagement or retention.", ["follow_up", "course_delivery"]),
    option("coach_goal_scale", "Build a more scalable coaching or education system.", ["multiple_offers", "pipeline"]),
  ]),
  question("q3_current_journey", "How do people currently discover and join your offer?", [
    option("coach_journey_social_dm", "Mostly through social media or direct messages.", ["lead_generation"]),
    option("coach_journey_unclear_website", "Through a website, but the next step is unclear.", ["credibility", "lead_generation"]),
    option("coach_journey_weak_funnel", "Through a landing page or funnel that needs improvement.", ["lead_generation", "follow_up"]),
    option("coach_journey_manual_booking_checkout", "Through a booking or checkout tool with several manual steps.", ["booking", "checkout", "follow_up"]),
    option("coach_journey_disconnected", "Through several disconnected platforms.", ["disconnected_tools", "integration"]),
    option("coach_journey_structured_improve", "We already have a structured system but need to improve it.", ["integration"]),
  ]),
  question("q4_bottlenecks", "Where does your customer or student journey currently break down?", [
    option("coach_blocker_leads", "Not enough qualified leads.", ["lead_generation"]),
    option("coach_blocker_conversion", "People are interested but do not book or enroll.", ["booking", "enrollment"]),
    option("coach_blocker_follow_up", "Follow-up is manual or inconsistent.", ["follow_up"]),
    option("coach_blocker_payment", "Payment or enrollment has too many steps.", ["checkout", "enrollment"]),
    option("coach_blocker_onboarding", "Student onboarding is disorganized.", ["onboarding"]),
    option("coach_blocker_access", "Course or resources are difficult to access.", ["course_delivery"]),
    option("coach_blocker_retention", "Student engagement or retention is low.", ["follow_up", "course_delivery"]),
    option("coach_blocker_tools", "We use too many disconnected tools.", ["disconnected_tools", "integration"]),
  ], "multiple", "audience", "Choose up to two.", 2),
  demandQuestion,
  question("q6_customer_requirements", "What should customers be able to do without you or your team manually handling every step?", [
    option("coach_customer_learn_offer", "Learn about my offer or program.", ["credibility"]),
    option("coach_customer_apply", "Submit an application or inquiry.", ["lead_generation"]),
    option("coach_customer_book", "Book a discovery or coaching call.", ["booking"]),
    option("coach_customer_pay_enroll", "Pay or enroll online.", ["checkout", "enrollment"]),
    option("coach_customer_payment_plan", "Choose a payment plan.", ["checkout"]),
    option("coach_customer_follow_up", "Receive automatic follow-up.", ["follow_up"]),
    option("coach_customer_onboarding", "Complete onboarding information.", ["onboarding"]),
    option("coach_customer_course_access", "Access a course or resource library.", ["course_delivery"]),
    option("coach_customer_community", "Join a membership or community.", ["course_delivery", "portal"]),
    option("coach_customer_portal", "Access a student or client portal.", ["portal"]),
  ], "multiple", "audience", "Select every capability required for the first version."),
  question("q7_post_conversion", "Once someone becomes a client or student, what needs to happen next?", [
    option("coach_after_confirmation", "Enrollment confirmation.", ["enrollment", "follow_up"]),
    option("coach_after_payment_plan", "Payment or payment-plan setup.", ["checkout"]),
    option("coach_after_welcome", "Welcome email.", ["follow_up"]),
    option("coach_after_intake", "Intake questionnaire.", ["onboarding"]),
    option("coach_after_scheduling", "Session or calendar scheduling.", ["booking"]),
    option("coach_after_course", "Course access.", ["course_delivery"]),
    option("coach_after_resources", "Resource-library access.", ["course_delivery"]),
    option("coach_after_community", "Community access.", ["portal"]),
    option("coach_after_progress", "Student progress tracking.", ["dashboard"]),
    option("coach_after_assignments", "Assignments or quizzes.", ["course_delivery"]),
    option("coach_after_certificates", "Certificates.", ["course_delivery"]),
    option("coach_after_renewal", "Renewal or membership management.", ["follow_up", "pipeline"]),
  ], "multiple"),
  question("q8_scope", "Which of these are part of your business?", [
    option("coach_scope_multiple_offers", "Multiple offers or programs.", ["multiple_offers"]),
    option("coach_scope_access_levels", "Different student access levels.", ["multiple_roles", "portal"]),
    option("coach_scope_subscriptions", "Installments or subscriptions.", ["checkout"]),
    option("coach_scope_cohorts", "Cohorts or specific enrollment dates.", ["enrollment"]),
    option("coach_scope_multiple_instructors", "Multiple coaches or instructors.", ["multiple_roles"]),
    option("coach_scope_progress", "Course-progress tracking.", ["dashboard", "course_delivery"]),
    option("coach_scope_community", "Community or membership access.", ["portal"]),
    option("coach_scope_assessments", "Assessments or certificates.", ["course_delivery"]),
    option("coach_scope_behavior_follow_up", "Different follow-up based on student behavior.", ["follow_up"]),
    option("coach_scope_migration", "Existing course or student migration.", ["migration"]),
    option("coach_scope_integrations", "External tools that need to connect.", ["integration"]),
  ], "multiple"),
  timelineQuestion,
  platformQuestion,
  question("q11_addons", "What additional support would make this project more complete for you?", [
    option("coach_addon_copy", "Offer or program conversion copywriting.", ["no_system_effect"], { addonKey: "conversion_copywriting" }),
    option("coach_addon_application", "Application or qualification setup.", ["lead_generation"]),
    option("coach_addon_webinar", "Webinar or workshop funnel.", ["enrollment", "multiple_offers"]),
    option("coach_addon_booking", "Advanced booking workflow.", ["booking"], { addonKey: "advanced_booking_setup" }),
    option("coach_addon_payment_plan", "Payment-plan setup.", ["checkout"], { addonKey: "checkout_payment_integration" }),
    option("coach_addon_course", "Course setup.", ["course_delivery"], { addonKey: "platform_membership_course_area" }),
    option("coach_addon_course_migration", "Existing course migration.", ["migration"], { addonKey: "content_data_migration" }),
    option("coach_addon_membership", "Membership or community setup.", ["portal", "course_delivery"]),
    option("coach_addon_cohort", "Cohort enrollment automation.", ["enrollment", "follow_up"]),
    option("coach_addon_onboarding", "Student onboarding sequence.", ["onboarding"], { addonKey: "advanced_onboarding_workflow" }),
    option("coach_addon_reactivation", "Student engagement or reactivation sequence.", ["follow_up"], { addonKey: "additional_email_automation" }),
    option("coach_addon_assessments", "Assessments, quizzes, or certificates.", ["course_delivery"]),
    option("coach_addon_resources", "Resource-library setup.", ["course_delivery"]),
    option("coach_addon_zoom", "Zoom or calendar integration.", ["integration"], { addonKey: "standard_third_party_integration" }),
    option("coach_addon_data_migration", "Existing student-data migration.", ["migration"], { addonKey: "content_data_migration" }),
    option("coach_addon_none", "No additional support for now.", ["no_system_effect"]),
  ], "multiple"),
] as const;

const serviceQuestions = [
  question("q1_business_model", "How do clients usually work with you?", [
    option("service_model_appointment", "Appointment-based service.", ["booking"]),
    option("service_model_consultation", "Consultation-based service.", ["booking", "pipeline"]),
    option("service_model_project", "Project-based service.", ["pipeline", "onboarding"]),
    option("service_model_retainer", "Recurring or retainer service.", ["pipeline", "follow_up"]),
    option("service_model_field", "Local or field service.", ["booking", "pipeline"]),
    option("service_model_multiple", "Multiple services, staff members, or locations.", ["multiple_offers", "multiple_roles"]),
  ]),
  question("q2_goal", "What would you most like your business to achieve?", [
    option("service_goal_inquiries", "Receive more qualified inquiries.", ["lead_generation"]),
    option("service_goal_bookings", "Book more appointments or consultations.", ["booking", "lead_generation"]),
    option("service_goal_no_shows", "Reduce no-shows and repetitive follow-up.", ["booking", "follow_up"]),
    option("service_goal_delivery", "Organize client intake and service delivery.", ["onboarding", "pipeline", "dashboard"]),
    option("service_goal_repeat", "Generate more repeat business or reactivate past clients.", ["follow_up", "pipeline"]),
    option("service_goal_scale", "Build a more scalable client-management system.", ["pipeline", "dashboard"]),
  ]),
  question("q3_current_journey", "How do clients currently go from interested to booked or confirmed?", [
    option("service_journey_social_phone", "Social media, phone calls, or direct messages.", ["lead_generation"]),
    option("service_journey_website_manual", "A basic website followed by manual communication.", ["credibility", "follow_up"]),
    option("service_journey_booking_manual", "A booking tool followed by manual follow-up.", ["booking", "follow_up"]),
    option("service_journey_form_manual", "A form followed by several manual steps.", ["lead_generation", "onboarding"]),
    option("service_journey_disconnected", "Several disconnected tools or spreadsheets.", ["disconnected_tools", "pipeline"]),
    option("service_journey_structured_improve", "We already have a structured system but need to improve it.", ["integration", "pipeline"]),
  ]),
  question("q4_bottlenecks", "Where does your client journey currently break down?", [
    option("service_blocker_offer", "Visitors do not clearly understand the service.", ["credibility"]),
    option("service_blocker_booking", "Inquiries do not consistently become bookings.", ["booking", "lead_generation"]),
    option("service_blocker_qualification", "Qualification takes too much manual communication.", ["lead_generation", "pipeline"]),
    option("service_blocker_admin", "Intake, reminders, and follow-up take too much time.", ["onboarding", "follow_up"]),
    option("service_blocker_payment", "Deposits or payment confirmation slow down bookings.", ["checkout", "booking"]),
    option("service_blocker_scattered", "Client information is scattered.", ["pipeline"]),
    option("service_blocker_status", "Project or service statuses are hard to track.", ["dashboard", "pipeline"]),
    option("service_blocker_retention", "Existing customers are not consistently followed up.", ["follow_up"]),
  ], "multiple", "audience", "Choose up to two.", 2),
  demandQuestion,
  question("q6_customer_requirements", "What should customers be able to do without you or your team manually handling every step?", [
    option("service_customer_learn", "Learn about my services.", ["credibility"]),
    option("service_customer_inquiry", "Submit an inquiry.", ["lead_generation"]),
    option("service_customer_qualify", "Complete a qualification form.", ["lead_generation", "pipeline"]),
    option("service_customer_book", "Book an appointment or consultation.", ["booking"]),
    option("service_customer_pay", "Pay a deposit or service fee.", ["checkout"]),
    option("service_customer_reminders", "Receive automatic reminders.", ["follow_up"]),
    option("service_customer_intake", "Complete client intake.", ["onboarding"]),
    option("service_customer_next_steps", "Track next steps.", ["pipeline"]),
    option("service_customer_resources", "Access documents or resources.", ["portal"]),
    option("service_customer_portal", "Access a client portal.", ["portal", "dashboard"]),
  ], "multiple", "audience", "Select every capability required for the first version."),
  question("q7_post_conversion", "Once someone books or hires you, what needs to happen next?", [
    option("service_after_intake", "Client intake.", ["onboarding"]),
    option("service_after_payment", "Deposit or payment.", ["checkout"]),
    option("service_after_estimate", "Estimate or proposal.", ["pipeline"]),
    option("service_after_contract", "Contract or signature.", ["approvals"]),
    option("service_after_reminders", "Appointment reminders.", ["booking", "follow_up"]),
    option("service_after_documents", "Document collection.", ["portal"]),
    option("service_after_assignment", "Staff assignment.", ["multiple_roles", "pipeline"]),
    option("service_after_status", "Service or project status tracking.", ["dashboard", "pipeline"]),
    option("service_after_follow_up", "Follow-up after service.", ["follow_up"]),
    option("service_after_review", "Review request.", ["follow_up"]),
    option("service_after_rebooking", "Rebooking.", ["booking", "follow_up"]),
    option("service_after_recurring", "Recurring-service reminders.", ["follow_up"]),
    option("service_after_portal", "Client portal access.", ["portal"]),
  ], "multiple"),
  question("q8_scope", "Which of these are part of your service operation?", [
    option("service_scope_multiple_services", "Multiple services.", ["multiple_offers"]),
    option("service_scope_team", "Multiple team members.", ["multiple_roles"]),
    option("service_scope_locations", "Multiple locations.", ["multiple_offers"]),
    option("service_scope_assignment", "Leads need to be assigned to different staff.", ["multiple_roles", "pipeline"]),
    option("service_scope_appointment_types", "Different appointment types or durations.", ["booking"]),
    option("service_scope_resources", "Room or resource availability.", ["booking"]),
    option("service_scope_documents", "Estimates, proposals, or contracts.", ["approvals", "pipeline"]),
    option("service_scope_payments", "Deposits or installment payments.", ["checkout"]),
    option("service_scope_pipelines", "Different client pipelines.", ["pipeline", "multiple_offers"]),
    option("service_scope_access", "Different team access levels.", ["multiple_roles"]),
    option("service_scope_recurring", "Recurring clients.", ["follow_up", "pipeline"]),
    option("service_scope_integrations", "External tools that need to connect.", ["integration"]),
    option("service_scope_compliance", "Special privacy or compliance requirements.", ["multiple_roles"]),
  ], "multiple"),
  timelineQuestion,
  platformQuestion,
  question("q11_addons", "What additional support would make this project more complete for you?", [
    option("service_addon_copy", "Service conversion copywriting.", ["no_system_effect"], { addonKey: "conversion_copywriting" }),
    option("service_addon_booking", "Advanced booking configuration.", ["booking"], { addonKey: "advanced_booking_setup" }),
    option("service_addon_staff", "Multi-staff scheduling.", ["multiple_roles", "booking"]),
    option("service_addon_resources", "Room or resource scheduling.", ["booking"]),
    option("service_addon_estimate", "Estimate or quotation workflow.", ["pipeline"]),
    option("service_addon_contract", "Contract or e-signature workflow.", ["approvals", "integration"]),
    option("service_addon_payment", "Deposit or payment setup.", ["checkout"], { addonKey: "checkout_payment_integration" }),
    option("service_addon_intake", "Client-intake workflow.", ["onboarding"], { addonKey: "advanced_onboarding_workflow" }),
    option("service_addon_reminders", "Appointment reminders.", ["follow_up"], { addonKey: "additional_email_automation" }),
    option("service_addon_rebooking", "Rebooking automation.", ["booking", "follow_up"]),
    option("service_addon_reviews", "Review or reputation workflow.", ["follow_up"]),
    option("service_addon_reactivation", "Past-lead reactivation.", ["follow_up", "pipeline"]),
    option("service_addon_migration", "CRM or client-data migration.", ["migration"], { addonKey: "content_data_migration" }),
    option("service_addon_portal", "Client-document portal.", ["portal"], { addonKey: "basic_custom_portal_module" }),
    option("service_addon_reporting", "Reporting or dashboard.", ["dashboard"], { addonKey: "custom_dashboard_reporting_module" }),
    option("service_addon_none", "No additional support for now.", ["no_system_effect"]),
  ], "multiple"),
] as const;

const customOrderQuestions = [
  question("q1_business_model", "What best describes what you sell?", [
    option("order_model_personalized", "Personalized products.", ["custom_orders"]),
    option("order_model_made_to_order", "Made-to-order products.", ["custom_orders", "order_tracking"]),
    option("order_model_quote_based", "Quote-based custom products.", ["custom_orders", "pipeline"]),
    option("order_model_event_packages", "Event or custom packages.", ["custom_orders", "multiple_offers"]),
    option("order_model_wholesale", "Wholesale or B2B custom orders.", ["custom_orders", "pipeline"]),
    option("order_model_several", "Several types of custom orders.", ["custom_orders", "multiple_offers"]),
  ]),
  question("q2_goal", "What would you most like your business to achieve?", [
    option("order_goal_inquiries", "Receive more qualified custom-order inquiries.", ["lead_generation", "custom_orders"]),
    option("order_goal_customization", "Make product customization easier.", ["custom_orders"]),
    option("order_goal_accuracy", "Reduce order mistakes and repetitive questions.", ["custom_orders", "follow_up"]),
    option("order_goal_operations", "Organize quotes, deposits, production, and customer updates.", ["pipeline", "order_tracking"]),
    option("order_goal_completion", "Increase completed orders without increasing manual admin.", ["checkout", "follow_up"]),
    option("order_goal_scale", "Build a scalable custom-order management system.", ["custom_orders", "dashboard"]),
  ]),
  question("q3_current_journey", "How do customers currently go from interested to confirmed order?", [
    option("order_journey_messages", "They message us and everything happens manually.", ["lead_generation", "custom_orders"]),
    option("order_journey_form_messages", "They submit a form and we continue through messages.", ["custom_orders", "follow_up"]),
    option("order_journey_online_manual_custom", "They order online but customization still happens manually.", ["checkout", "custom_orders"]),
    option("order_journey_store_split_ops", "We have an online store but quoting, approval, or production happens elsewhere.", ["disconnected_tools", "order_tracking"]),
    option("order_journey_disconnected", "We use several disconnected tools or spreadsheets.", ["disconnected_tools", "order_tracking"]),
    option("order_journey_structured_improve", "We already have a structured system but need to improve it.", ["integration", "order_tracking"]),
  ]),
  question("q4_bottlenecks", "Where does your order process usually get stuck?", [
    option("order_blocker_options", "Customers are unsure which options to choose.", ["credibility", "custom_orders"]),
    option("order_blocker_incomplete", "Order requirements arrive incomplete.", ["custom_orders"]),
    option("order_blocker_quotes", "Quotes take too long.", ["pipeline"]),
    option("order_blocker_payment", "Deposits or payment confirmation take too long.", ["checkout", "follow_up"]),
    option("order_blocker_scattered", "Order details are scattered across messages.", ["custom_orders", "pipeline"]),
    option("order_blocker_approvals", "Proofs, revisions, or approvals are difficult to track.", ["approvals", "order_tracking"]),
    option("order_blocker_production", "Production status is difficult to monitor.", ["order_tracking", "dashboard"]),
    option("order_blocker_updates", "Customers frequently ask for order updates.", ["follow_up", "order_tracking"]),
    option("order_blocker_inventory", "Inventory or material usage is difficult to monitor.", ["inventory"]),
  ], "multiple", "audience", "Choose up to two.", 2),
  demandQuestion,
  question("q6_customer_requirements", "What should customers be able to do without you or your team manually handling every step?", [
    option("order_customer_browse", "Browse products or service options.", ["credibility"]),
    option("order_customer_customize", "Choose customization options.", ["custom_orders"]),
    option("order_customer_upload", "Upload reference images or files.", ["custom_orders", "portal"]),
    option("order_customer_quote", "Request a quote.", ["lead_generation", "pipeline"]),
    option("order_customer_request", "Place an order request.", ["custom_orders"]),
    option("order_customer_deposit", "Pay a deposit.", ["checkout"]),
    option("order_customer_full_payment", "Pay the full amount.", ["checkout"]),
    option("order_customer_approve", "Approve a proof or mockup.", ["approvals"]),
    option("order_customer_updates", "Receive automatic status updates.", ["follow_up", "order_tracking"]),
    option("order_customer_track", "Track order status.", ["order_tracking", "portal"]),
    option("order_customer_reorder", "View previous orders or reorder.", ["portal", "pipeline"]),
  ], "multiple", "audience", "Select every capability required for the first version."),
  question("q7_post_conversion", "Once a customer wants to order, what needs to happen before the order is completed?", [
    option("order_after_details", "Collect customization details.", ["custom_orders"]),
    option("order_after_uploads", "Receive reference images or files.", ["portal"]),
    option("order_after_quote", "Prepare a quote.", ["pipeline"]),
    option("order_after_deposit", "Collect a deposit.", ["checkout"]),
    option("order_after_proof", "Create a proof or mockup.", ["approvals"]),
    option("order_after_approval", "Get customer approval.", ["approvals"]),
    option("order_after_revisions", "Handle revisions.", ["approvals"]),
    option("order_after_production", "Track production stages.", ["order_tracking"]),
    option("order_after_inventory", "Track materials or inventory.", ["inventory"]),
    option("order_after_balance", "Collect the remaining balance.", ["checkout"]),
    option("order_after_delivery", "Schedule pickup or delivery.", ["order_tracking"]),
    option("order_after_updates", "Send status updates.", ["follow_up", "order_tracking"]),
    option("order_after_tracking", "Allow customer order tracking.", ["portal", "order_tracking"]),
    option("order_after_reorder", "Save the order for future reordering.", ["pipeline"]),
  ], "multiple"),
  question("q8_scope", "Which of these are part of your order workflow?", [
    option("order_scope_options", "Many product options or add-ons.", ["custom_orders"]),
    option("order_scope_dynamic_pricing", "Pricing changes depending on selected options.", ["custom_orders", "approvals"]),
    option("order_scope_balances", "Deposits and remaining balances.", ["checkout"]),
    option("order_scope_proof", "Proof or mockup approval.", ["approvals"]),
    option("order_scope_revisions", "Customer revisions.", ["approvals"]),
    option("order_scope_production", "Multiple production stages.", ["order_tracking"]),
    option("order_scope_inventory", "Inventory or raw-material tracking.", ["inventory"]),
    option("order_scope_employees", "Multiple employees.", ["multiple_roles"]),
    option("order_scope_permissions", "Different staff permissions.", ["multiple_roles"]),
    option("order_scope_delivery_calculation", "Delivery-fee calculations.", ["custom_orders"]),
    option("order_scope_branches", "Multiple branches.", ["multiple_roles", "multiple_offers"]),
    option("order_scope_wholesale", "Wholesale pricing.", ["custom_orders"]),
    option("order_scope_reports", "Custom reports.", ["dashboard"]),
    option("order_scope_integrations", "Existing POS, accounting, or shipping tools.", ["integration"]),
    option("order_scope_portal", "Customer portal.", ["portal"]),
  ], "multiple"),
  timelineQuestion,
  platformQuestion,
  question("q11_addons", "What additional support would make this project more complete for you?", [
    option("order_addon_copy", "Product copywriting.", ["no_system_effect"], { addonKey: "conversion_copywriting" }),
    option("order_addon_images", "Product image optimization.", ["no_system_effect"], { addonKey: "image_editing_optimization" }),
    option("order_addon_catalog", "Product catalog setup.", ["credibility"]),
    option("order_addon_options", "Custom product-option setup.", ["custom_orders"]),
    option("order_addon_pricing", "Conditional pricing setup.", ["custom_orders", "approvals"]),
    option("order_addon_quote", "Quote workflow.", ["pipeline"]),
    option("order_addon_payment", "Deposit or balance workflow.", ["checkout"], { addonKey: "checkout_payment_integration" }),
    option("order_addon_uploads", "Customer image or file uploads.", ["portal"]),
    option("order_addon_approval", "Proof or mockup approval workflow.", ["approvals"]),
    option("order_addon_revisions", "Revision workflow.", ["approvals"]),
    option("order_addon_production", "Production board.", ["order_tracking", "dashboard"], { addonKey: "custom_order_management_module" }),
    option("order_addon_portal", "Customer order-status portal.", ["portal", "order_tracking"], { addonKey: "basic_custom_portal_module" }),
    option("order_addon_delivery", "Delivery or pickup scheduling.", ["order_tracking"]),
    option("order_addon_delivery_fee", "Delivery-fee calculation.", ["custom_orders"]),
    option("order_addon_history", "Customer history or reordering.", ["pipeline"]),
    option("order_addon_inventory", "Inventory or raw-material tracking.", ["inventory"], { addonKey: "inventory_production_module" }),
    option("order_addon_roles", "Staff or role management.", ["multiple_roles"]),
    option("order_addon_integrations", "POS, accounting, or shipping integration.", ["integration"], { addonKey: "standard_third_party_integration" }),
    option("order_addon_migration", "Existing order-data migration.", ["migration"], { addonKey: "content_data_migration" }),
    option("order_addon_none", "No additional support for now.", ["no_system_effect"]),
  ], "multiple"),
] as const;

const definition = (
  audienceKey: AudienceKey,
  label: string,
  description: string,
  resultLabel: string,
  questions: readonly QuestionDefinition[],
): QuizDefinition => ({ audienceKey, label, description, resultLabel, version: CORTEX_VERSION, questionSetVersion: QUESTION_SET_VERSION, questions });

export const QUIZ_DEFINITIONS: Record<AudienceKey, QuizDefinition> = {
  coaches_educators: definition("coaches_educators", "Coaches & Educators", "Sell expertise, enroll students, and deliver a smoother learning journey.", "Book and Enroll", coachesQuestions),
  service_businesses: definition("service_businesses", "Service-Based Businesses", "Turn inquiries into appointments and reduce repetitive admin work.", "Attract and Book", serviceQuestions),
  custom_order_businesses: definition("custom_order_businesses", "Custom-Order Businesses", "Simplify custom orders, payments, updates, and customer tracking.", "Order and Organize", customOrderQuestions),
};

export function getQuestionDefinition(audienceKey: AudienceKey, questionKey: string) {
  return QUIZ_DEFINITIONS[audienceKey].questions.find((item) => item.key === questionKey);
}
