import { CATALOG_VERSION, type AddonDefinition, type PackageDefinition } from "./types";

export { CATALOG_VERSION };

export const PACKAGE_CATALOG: readonly PackageDefinition[] = [
  {
    offerKey: "platform_launch",
    name: "Launch System",
    buildRoute: "platform",
    supportedPlatforms: ["systeme_io", "gohighlevel"],
    basePriceUsd: 1500,
    level: 1,
    description: "Best for one offer, one audience, and one primary conversion action.",
    includedCapabilityKeys: ["responsive_build", "lead_form", "confirmation_page", "basic_booking_or_checkout", "basic_email_follow_up", "basic_analytics"],
    includedFeatures: ["Strategy and conversion-path planning for one offer", "One landing page or compact conversion website of up to five core sections", "Responsive desktop, tablet, and mobile setup", "One lead, application, or inquiry form", "One thank-you or confirmation page", "One basic booking or checkout connection", "One confirmation email and one basic follow-up sequence of up to three emails", "Basic tags, contact fields, and segmentation", "Basic analytics and conversion-event setup", "Domain connection guidance", "Launch testing and handover"],
    integrationAllowance: 0,
    supportDays: 0,
    revisionRounds: 1,
  },
  {
    offerKey: "platform_growth",
    name: "Growth System",
    buildRoute: "platform",
    supportedPlatforms: ["systeme_io", "gohighlevel"],
    basePriceUsd: 2500,
    level: 2,
    description: "Best for a connected lead-to-booking, enrollment, or order journey.",
    includedCapabilityKeys: ["multi_step_funnel", "lead_qualification", "booking_or_checkout", "crm_pipeline", "email_follow_up", "basic_onboarding", "two_standard_integrations"],
    includedFeatures: ["Everything in Launch System where applicable", "Multi-step funnel or conversion website of up to five primary pages or steps", "Lead qualification or application flow", "Booking, checkout, enrollment, or deposit connection", "CRM pipeline with core stages", "Automated confirmation, reminders, and follow-up sequence of up to seven messages", "Basic onboarding workflow", "Audience or offer segmentation", "Up to two standard third-party integrations", "Funnel and pipeline testing", "Recorded handover or training session"],
    integrationAllowance: 2,
    supportDays: 0,
    revisionRounds: 2,
  },
  {
    offerKey: "platform_scale",
    name: "Scale System",
    buildRoute: "platform",
    supportedPlatforms: ["systeme_io", "gohighlevel"],
    basePriceUsd: 4000,
    level: 3,
    description: "Best for multiple offers, connected pipelines, and advanced platform-native automation.",
    includedCapabilityKeys: ["multiple_offers", "advanced_pipeline", "conditional_workflows", "extended_nurture", "platform_onboarding_area", "four_standard_integrations", "basic_reporting"],
    includedFeatures: ["Everything in Growth System where applicable", "Up to two offers, funnels, or audience paths", "Advanced pipeline stages and opportunity automation", "Conditional platform-native workflows", "Extended email or SMS nurture of up to twelve messages", "Platform-native client or student onboarding area where available", "Up to four standard integrations", "Basic reporting dashboard using available platform data", "Supported team access and permissions", "End-to-end quality assurance", "Training and 30-day post-launch technical support"],
    integrationAllowance: 4,
    supportDays: 30,
    revisionRounds: 2,
  },
  {
    offerKey: "custom_starter",
    name: "Custom Starter",
    buildRoute: "custom",
    supportedPlatforms: ["custom_app"],
    basePriceUsd: 3000,
    level: 1,
    description: "Best for a focused minimum viable product with one clear workflow.",
    includedCapabilityKeys: ["focused_module", "single_user_type_auth", "core_crud_status_workflow", "simple_admin_view", "basic_notification"],
    includedFeatures: ["Discovery session and simplified workflow map", "Custom responsive interface for one focused module", "Supabase project, database, and basic security setup", "Authentication for one primary user type", "One core create, view, edit, and status workflow", "Simple admin management view", "Basic validation and record search or filtering", "One basic notification or confirmation workflow", "Deployment and environment configuration", "Testing, handover, and 30-day technical support"],
    integrationAllowance: 0,
    supportDays: 30,
    revisionRounds: 1,
  },
  {
    offerKey: "custom_foundation",
    name: "Custom Foundation",
    buildRoute: "custom",
    supportedPlatforms: ["custom_app"],
    basePriceUsd: 5000,
    level: 2,
    description: "Best for a production-ready custom app with a connected admin and user experience.",
    includedCapabilityKeys: ["admin_and_user_auth", "two_core_workflows", "admin_dashboard", "file_upload", "two_standard_integrations", "basic_activity_history"],
    includedFeatures: ["Everything in Custom Starter where applicable", "Detailed workflow and data-model planning", "Supabase database, authentication, storage, and access policies", "Authentication for one primary user type plus admin", "Up to two connected core workflows", "Custom admin dashboard with operational status tracking", "File or image uploads", "Expanded search, filtering, and record management", "Up to two standard integrations", "Basic analytics and activity history", "Email notifications or workflow confirmations", "Testing, handover, and 30-day technical support"],
    integrationAllowance: 2,
    supportDays: 30,
    revisionRounds: 2,
  },
  {
    offerKey: "custom_growth",
    name: "Custom Growth",
    buildRoute: "custom",
    supportedPlatforms: ["custom_app"],
    basePriceUsd: 7500,
    level: 3,
    description: "Best for several connected workflows, portals, roles, and dashboards.",
    includedCapabilityKeys: ["three_user_roles", "basic_custom_portal_module", "custom_dashboard_reporting_module", "multiple_workflows", "three_standard_integrations", "operational_reporting"],
    includedFeatures: ["Everything in Custom Foundation where applicable", "Up to three permission-based user roles", "A client, student, customer, employee, or partner portal", "Multiple connected business workflows", "Advanced admin dashboard and status tracking", "File or document management", "Search, filtering, and operational reporting", "Up to three standard integrations", "Automated notifications and workflow triggers", "Audit-friendly activity history", "Supabase row-level security for supported roles", "Training and 60-day technical support"],
    integrationAllowance: 3,
    supportDays: 60,
    revisionRounds: 2,
  },
  {
    offerKey: "custom_complete",
    name: "Complete Custom System",
    buildRoute: "custom",
    supportedPlatforms: ["custom_app"],
    basePriceUsd: 10000,
    level: 4,
    description: "Best for complex operations, multiple departments, inventory, delivery, or specialized business rules.",
    includedCapabilityKeys: ["advanced_roles", "multiple_portals", "custom_approvals", "advanced_reporting", "complex_business_rules", "expanded_integrations", "inventory_production_module", "custom_order_management_module"],
    includedFeatures: ["Everything in Custom Growth where applicable", "Advanced roles and permissions", "Multiple portals or department workspaces", "Scoped inventory, production, order, delivery, or resource-management modules", "Custom approvals and multi-stage workflows", "Advanced reporting and management dashboards", "Complex calculations or business rules", "Expanded integration requirements", "Data migration planning where required", "Advanced Supabase relationships, storage policies, and server-side functions", "Security review and extended quality assurance", "Phased rollout plan", "Training and 90-day technical support"],
    integrationAllowance: 4,
    supportDays: 90,
    revisionRounds: 3,
    startingPrice: true,
    requiresScopeReview: true,
  },
] as const;

const addon = (
  addonKey: string,
  name: string,
  description: string,
  startingPriceUsd: number,
  pricingUnit: string,
  allowedBuildRoutes: AddonDefinition["allowedBuildRoutes"],
  includedInOfferKeys: readonly string[] = [],
  requiresScopeReview = false,
  recurringCostNote?: string,
): AddonDefinition => ({ addonKey, name, description, startingPriceUsd, pricingUnit, allowedBuildRoutes, includedInOfferKeys, requiresScopeReview, recurringCostNote });

export const ADDON_CATALOG: readonly AddonDefinition[] = [
  addon("conversion_copywriting", "Conversion copywriting", "Conversion copywriting for core pages or steps.", 500, "Up to five core pages/steps", ["platform", "custom"]),
  addon("additional_copywriting", "Additional copywriting", "Copywriting beyond the core included scope.", 150, "Per additional page/step", ["platform", "custom"]),
  addon("image_sourcing_selection", "Image sourcing and selection", "Image sourcing and selection for the project.", 200, "Per project set", ["platform", "custom"]),
  addon("image_editing_optimization", "Image editing and optimization", "Editing and web optimization for supplied or sourced images.", 300, "Up to 20 images", ["platform", "custom"]),
  addon("mini_brand_direction", "Mini brand direction", "Colors, typography, and a basic visual guide.", 400, "Colors, type, and basic visual guide", ["platform", "custom"]),
  addon("additional_page_step", "Additional landing/page step", "An additional standard landing page or funnel step.", 250, "Per standard page/step", ["platform", "custom"]),
  addon("advanced_booking_setup", "Advanced booking setup", "An advanced booking workflow.", 350, "Per booking workflow", ["platform", "custom"]),
  addon("checkout_payment_integration", "Checkout/payment integration", "A standard checkout or payment gateway flow.", 400, "Per standard gateway/flow", ["platform", "custom"], ["platform_launch", "platform_growth", "platform_scale"]),
  addon("additional_email_automation", "Additional email automation", "An additional email sequence.", 300, "Per sequence of up to five emails", ["platform", "custom"]),
  addon("sms_automation_setup", "SMS automation setup", "An SMS workflow; usage is billed separately.", 350, "Per workflow; usage billed separately", ["platform", "custom"], [], false, "SMS provider and message usage are paid separately."),
  addon("additional_crm_pipeline", "Additional CRM pipeline", "An additional CRM pipeline.", 500, "Per pipeline", ["platform", "custom"]),
  addon("advanced_onboarding_workflow", "Advanced onboarding workflow", "An advanced onboarding workflow.", 500, "Per workflow", ["platform", "custom"], ["platform_scale"]),
  addon("platform_membership_course_area", "Platform-native membership/course area", "A membership or course area using supported platform-native features.", 750, "Per area/program", ["platform"]),
  addon("basic_custom_portal_module", "Basic custom portal module", "A basic portal module for the Custom App route.", 1500, "Per module; Custom App route", ["custom"], ["custom_growth", "custom_complete"]),
  addon("custom_dashboard_reporting_module", "Custom dashboard/reporting module", "A custom dashboard or reporting module.", 1500, "Per module; Custom App route", ["custom"], ["custom_foundation", "custom_growth", "custom_complete"]),
  addon("custom_order_management_module", "Custom order-management module", "A custom order-management module.", 2000, "Per module; Custom App route", ["custom"]),
  addon("inventory_production_module", "Inventory/production module", "A custom inventory or production module.", 2500, "Starting price; Custom App route", ["custom"], [], true),
  addon("standard_third_party_integration", "Standard third-party integration", "A standard supported third-party integration.", 350, "Per integration", ["platform", "custom"], ["platform_growth", "platform_scale", "custom_foundation", "custom_growth", "custom_complete"]),
  addon("complex_custom_api_integration", "Complex/custom API integration", "A complex or custom API integration requiring review.", 750, "Per integration after review", ["platform", "custom"], [], true),
  addon("content_data_migration", "Content or data migration", "Content or data migration based on volume and cleanup needs.", 500, "Based on volume and cleanup", ["platform", "custom"], [], true),
  addon("additional_revision_round", "Additional revision round", "One additional revision round.", 300, "Per round", ["platform", "custom"]),
] as const;

export const PACKAGE_BY_KEY = new Map(PACKAGE_CATALOG.map((item) => [item.offerKey, item]));
export const ADDON_BY_KEY = new Map(ADDON_CATALOG.map((item) => [item.addonKey, item]));
