-- Phase 1 transactional tables. Catalog FKs and the quiz/lead back-link are
-- added later so migrations preserve relationship integrity without cycles.

create table public.site_visitors (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  first_touch_source text,
  first_touch_medium text,
  first_touch_campaign text,
  landing_path text not null,
  referrer_domain text,
  consent_status text not null default 'unknown',
  quiz_started_count integer not null default 0,
  quiz_completed_count integer not null default 0,
  booking_cta_click_count integer not null default 0,
  latest_quiz_session_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_visitors_owner_user_id_key unique (owner_user_id),
  constraint site_visitors_owner_user_id_fkey foreign key (owner_user_id) references auth.users(id) on delete restrict,
  constraint site_visitors_landing_path_check check (length(btrim(landing_path)) > 0),
  constraint site_visitors_seen_at_check check (last_seen_at >= first_seen_at),
  constraint site_visitors_consent_status_check check (consent_status in ('unknown', 'granted', 'denied', 'withdrawn')),
  constraint site_visitors_quiz_started_count_check check (quiz_started_count >= 0),
  constraint site_visitors_quiz_completed_count_check check (quiz_completed_count >= 0),
  constraint site_visitors_booking_cta_click_count_check check (booking_cta_click_count >= 0)
);

create table public.portfolio_sessions (
  id uuid primary key default gen_random_uuid(),
  visitor_id uuid not null,
  owner_user_id uuid not null,
  started_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  landing_path text not null,
  audience_key text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  referrer_domain text,
  device_category text,
  result_viewed boolean not null default false,
  booking_cta_clicked boolean not null default false,
  converted_to_lead boolean not null default false,
  lead_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint portfolio_sessions_visitor_id_fkey foreign key (visitor_id) references public.site_visitors(id) on delete restrict,
  constraint portfolio_sessions_owner_user_id_fkey foreign key (owner_user_id) references auth.users(id) on delete restrict,
  constraint portfolio_sessions_landing_path_check check (length(btrim(landing_path)) > 0),
  constraint portfolio_sessions_activity_check check (last_activity_at >= started_at),
  constraint portfolio_sessions_device_category_check check (device_category is null or device_category in ('desktop', 'tablet', 'mobile', 'other'))
);

create table public.quiz_sessions (
  id uuid primary key default gen_random_uuid(),
  visitor_id uuid not null,
  owner_user_id uuid not null,
  portfolio_session_id uuid not null,
  question_set_id uuid not null,
  lead_id uuid,
  audience_key text not null,
  question_set_version integer not null,
  status text not null default 'in_progress',
  current_step integer not null default 0,
  last_completed_step integer not null default 0,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  last_activity_at timestamptz not null default now(),
  resume_expires_at timestamptz not null default (now() + interval '30 days'),
  resume_count integer not null default 0,
  last_resumed_at timestamptz,
  answers jsonb not null default '{}'::jsonb,
  acquisition_need_score integer not null default 0,
  automation_need_score integer not null default 0,
  system_complexity_score integer not null default 0,
  website_score integer not null default 0,
  funnel_score integer not null default 0,
  automation_score integer not null default 0,
  crm_score integer not null default 0,
  custom_app_score integer not null default 0,
  systeme_fit_score integer not null default 0,
  ghl_fit_score integer not null default 0,
  custom_build_fit_score integer not null default 0,
  readiness_level text,
  recommended_build_route text,
  recommended_platform text,
  recommended_offer_key text,
  primary_solution_type text,
  supporting_solution_types text[] not null default '{}'::text[],
  selected_addon_keys text[] not null default '{}'::text[],
  priced_addons jsonb not null default '[]'::jsonb,
  base_price_usd numeric(12,2) not null default 0,
  addon_total_usd numeric(12,2) not null default 0,
  adjustment_total_usd numeric(12,2) not null default 0,
  estimated_project_investment_usd numeric(12,2) not null default 0,
  result_snapshot jsonb,
  result_viewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quiz_sessions_visitor_id_fkey foreign key (visitor_id) references public.site_visitors(id) on delete restrict,
  constraint quiz_sessions_owner_user_id_fkey foreign key (owner_user_id) references auth.users(id) on delete restrict,
  constraint quiz_sessions_portfolio_session_id_fkey foreign key (portfolio_session_id) references public.portfolio_sessions(id) on delete restrict,
  constraint quiz_sessions_status_check check (status in ('in_progress', 'completed', 'restarted', 'expired', 'abandoned')),
  constraint quiz_sessions_version_check check (question_set_version > 0),
  constraint quiz_sessions_steps_check check (current_step >= 0 and last_completed_step >= 0 and last_completed_step <= current_step),
  constraint quiz_sessions_activity_check check (last_activity_at >= started_at),
  constraint quiz_sessions_resume_expiry_check check (resume_expires_at > last_activity_at),
  constraint quiz_sessions_resume_count_check check (resume_count >= 0),
  constraint quiz_sessions_answers_check check (jsonb_typeof(answers) = 'object' and pg_column_size(answers) <= 65536),
  constraint quiz_sessions_priced_addons_check check (jsonb_typeof(priced_addons) = 'array'),
  constraint quiz_sessions_scores_check check (
    acquisition_need_score >= 0 and automation_need_score >= 0 and system_complexity_score >= 0 and
    website_score >= 0 and funnel_score >= 0 and automation_score >= 0 and crm_score >= 0 and
    custom_app_score >= 0 and systeme_fit_score >= 0 and ghl_fit_score >= 0 and custom_build_fit_score >= 0
  ),
  constraint quiz_sessions_money_check check (
    base_price_usd >= 0 and addon_total_usd >= 0 and estimated_project_investment_usd >= 0
  ),
  constraint quiz_sessions_completion_check check (
    (status = 'completed' and completed_at is not null and result_snapshot is not null)
    or status <> 'completed'
  )
);

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  visitor_id uuid,
  first_name text not null,
  last_name text,
  email text not null,
  phone text,
  business_name text,
  business_url text,
  audience_key text,
  acquisition_source text,
  source_portfolio_session_id uuid,
  source_quiz_session_id uuid,
  crm_stage text not null default 'new',
  lead_status text not null default 'open',
  assigned_to_user_id uuid,
  last_contact_at timestamptz,
  lost_reason text,
  notes_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint leads_visitor_id_fkey foreign key (visitor_id) references public.site_visitors(id) on delete set null,
  constraint leads_source_portfolio_session_id_fkey foreign key (source_portfolio_session_id) references public.portfolio_sessions(id) on delete set null,
  constraint leads_source_quiz_session_id_fkey foreign key (source_quiz_session_id) references public.quiz_sessions(id) on delete set null,
  constraint leads_assigned_to_user_id_fkey foreign key (assigned_to_user_id) references auth.users(id) on delete set null,
  constraint leads_source_quiz_session_id_key unique (source_quiz_session_id),
  constraint leads_first_name_check check (length(btrim(first_name)) between 1 and 120),
  constraint leads_email_check check (email = lower(btrim(email)) and email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  constraint leads_phone_check check (phone is null or length(btrim(phone)) between 7 and 40),
  constraint leads_business_url_check check (business_url is null or business_url ~* '^https?://[^[:space:]]+$'),
  constraint leads_crm_stage_check check (length(btrim(crm_stage)) > 0),
  constraint leads_lead_status_check check (length(btrim(lead_status)) > 0)
);

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null,
  visitor_id uuid,
  portfolio_session_id uuid,
  quiz_session_id uuid,
  booking_provider text not null,
  external_booking_id text,
  scheduled_start timestamptz not null,
  scheduled_end timestamptz not null,
  time_zone text not null,
  status text not null default 'scheduled',
  meeting_url text,
  rescheduled_from_booking_id uuid,
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_lead_id_fkey foreign key (lead_id) references public.leads(id) on delete restrict,
  constraint bookings_visitor_id_fkey foreign key (visitor_id) references public.site_visitors(id) on delete set null,
  constraint bookings_portfolio_session_id_fkey foreign key (portfolio_session_id) references public.portfolio_sessions(id) on delete set null,
  constraint bookings_quiz_session_id_fkey foreign key (quiz_session_id) references public.quiz_sessions(id) on delete set null,
  constraint bookings_rescheduled_from_booking_id_fkey foreign key (rescheduled_from_booking_id) references public.bookings(id) on delete set null,
  constraint bookings_provider_check check (length(btrim(booking_provider)) > 0),
  constraint bookings_schedule_check check (scheduled_end > scheduled_start),
  constraint bookings_time_zone_check check (length(btrim(time_zone)) > 0),
  constraint bookings_status_check check (status in ('scheduled', 'completed', 'cancelled', 'no_show')),
  constraint bookings_meeting_url_check check (meeting_url is null or meeting_url ~* '^https?://[^[:space:]]+$')
);

create table public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid,
  event_name text not null,
  occurred_at timestamptz not null default now(),
  visitor_id uuid,
  portfolio_session_id uuid,
  quiz_session_id uuid,
  lead_id uuid,
  audience_key text,
  page_path text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint analytics_events_owner_user_id_fkey foreign key (owner_user_id) references auth.users(id) on delete set null,
  constraint analytics_events_visitor_id_fkey foreign key (visitor_id) references public.site_visitors(id) on delete set null,
  constraint analytics_events_portfolio_session_id_fkey foreign key (portfolio_session_id) references public.portfolio_sessions(id) on delete set null,
  constraint analytics_events_quiz_session_id_fkey foreign key (quiz_session_id) references public.quiz_sessions(id) on delete set null,
  constraint analytics_events_lead_id_fkey foreign key (lead_id) references public.leads(id) on delete set null,
  constraint analytics_events_name_check check (length(btrim(event_name)) between 1 and 80),
  constraint analytics_events_properties_check check (jsonb_typeof(properties) = 'object' and pg_column_size(properties) <= 8192)
);
